### ISSUE TITLE
Missing (a, b) tuple type instance in FromField

### ISSUE THREAD

**Issue by victoredwardocallaghan** [lpsmith/postgresql-simple#156] opened 2015-07-16 03:13 UTC
Hi,

I am just creating this as a separate issue.. Should we perhaps add the following instance?

```Haskell
-- | instance to handle (a, b) e.g., (Double, Double)
instance (FromField a, FromField b) => FromField (a, b) where
  fromField = fromField
```

Hopefully I got this correct?

Kind Regards,
Edward.

**Comment by lpsmith** [comment] 2015-07-17 20:50
Duplicate of #154

**Closed by lpsmith** 2015-07-17 20:50 UTC
